### ISSUE TITLE
HTTP read timeout too short for New Jersey source

### ISSUE THREAD

**Issue by missinglink** [openaddresses/pyesridump#29] opened 2016-10-19 09:44 UTC
``` bash
2016-10-19 11:14:44,848 - cli.esridump - INFO - Built 2950 requests using resultOffset method
Traceback (most recent call last):
  File "/usr/local/bin/esri2geojson", line 9, in <module>
    load_entry_point('esridump==1.4.1', 'console_scripts', 'esri2geojson')()
  File "build/bdist.linux-x86_64/egg/esridump/cli.py", line 93, in main
  File "build/bdist.linux-x86_64/egg/esridump/dumper.py", line 365, in __iter__
esridump.errors.EsriDownloadError: ('Could not connect to URL', ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='geodata.state.nj.us', port=80): Read timed out. (read timeout=30)",),))
```

is it possible to increase `read timeout=30` from the CLI?

**Comment by iandees** [comment] 2016-10-19 13:20
It's not possible right now, but it can be.

**Comment by missinglink** [comment] 2016-10-19 14:36
re: the title, I don't believe it's specific to the NJ source is it? I'm just using the `pyesridump` CLI with a URL as the first arg.

**Comment by iandees** [comment] 2016-10-19 14:38
Yup, the New Jersey server is particularly slow so it's going to show this more obviously. The fix for this will be general to all servers, but the problem is specific to New Jersey.

**Comment by missinglink** [comment] 2016-10-19 14:47
:+1:

**Closed** 2018-05-16 20:59 UTC
